apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}