apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
  namespace: vault
spec:
  provider: azure
  secretObjects:
  - secretName: demo-secret
    type: Opaque
    data:
    - objectName: "key1"
      key: key1
    - objectName: "key2"
      key: key2
    - objectName: "key3 "
      key: key3 
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "$aksManagedIdentityId"
    keyvaultName: "`<name-key-vault>`"    
    objects: |
      array:
        - |
          objectName: key1
          objectType: secret
        - |
          objectName: key2          
          objectType: secret
        - |
          objectName: key3               
          objectType: secret                    
    tenantId: "`<Tenant-ID>`"