variables:
  DOCKER_IMAGE: $DOCKER_REPO:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
  DOCKER_IMAGE_LATEST: $DOCKER_REPO:$CI_COMMIT_REF_NAME
  SERVICE: payline

stages:
  - run-service1
  - run-service2
  - triggers
  - test
  - build
  - dockerize
  - deploy
  - notification_success
  - notification_failed
  - dependencycheck
  - notify-dependencycheck

service1:
  rules:
    - changes:
        - service1/*
  trigger:
    include: 
      - local: service1/.gitlab-ci.yml

service2:
  rules:
    - changes:
        - service2/*
  trigger:
    include:      
      - local: service2/.gitlab-ci.yml